name: Linting
on: 
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout CTFd
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with: 
        repository: CTFd/CTFd
        ref: d6fc367187fc49134cfffe89fd1523162d29836a # 3.8.2

    - name: Checkout CTFd-chall-manager
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: CTFd/plugins/ctfd_chall_manager

    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.11' # CTFd python version
      
    - name: Install Python deps
      run: |
        pip install -r requirements.txt
    
    - name: Install Python linter
      run: |
        pip install -r CTFd/plugins/ctfd_chall_manager/linting.txt
      
    - name: Run formatter & linters
      run: |
        cd CTFd/plugins/ctfd_chall_manager
        isort --profile=black --check-only .
        black --check --diff .
        pylint . */*.py
