name: Linting
on: 
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout CTFd
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with: 
        repository: CTFd/CTFd
        ref: 82774a875b66325430cad41538300b8b33000d96 # 3.8.1

    - name: Checkout CTFd-chall-manager
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        path: CTFd/plugins/ctfd_chall_manager

    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.11' # CTFd python version
      
    - name: Install Python deps
      run: |
        pip install -r requirements.txt
    
    - name: Install Python linter
      run: |
        pip install -r CTFd/plugins/ctfd_chall_manager/linting.txt
      
    - name: Run formatter & linters
      run: |
        cd CTFd/plugins/ctfd_chall_manager
        isort --profile=black --check-only .
        black --check --diff .
        pylint . */*.py
